# Generated by Django 5.0.4 on 2024-07-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disc',
            options={'verbose_name': 'Disc', 'verbose_name_plural': 'Discs'},
        ),
    ]
